# Generated by Django 4.1.5 on 2023-01-06 03:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='GPA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, validators=[django.core.validators.MaxValueValidator(12.0), django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='classes',
            name='completed',
            field=models.BooleanField(blank=True),
        ),
    ]
