# Generated by Django 4.1.5 on 2023-01-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_classes_gpa_alter_classes_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
