# Generated by Django 4.1.5 on 2023-01-06 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_classes_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='GPA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MaxValueValidator(12.0), django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
